// <auto-generated />
namespace RoomMe.Webservice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v7_Auth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v7_Auth));
        
        string IMigrationMetadata.Id
        {
            get { return "201507180808120_v7_Auth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
